2022/03/28 08:42:00 [error] 467#467: *2896 connect() failed (111: Connection refused) while connecting to upstream, client: 10.10.0.40, server: moodle.cpnv-srw3.ch, request: "GET / HTTP/2.0", upstream: "http://172.20.0.11:80/", host: "moodle.cpnv-srw3.ch", referrer: "https://proxy.cpnv-srw3.ch/"
2022/03/28 08:42:00 [error] 467#467: *2896 connect() failed (111: Connection refused) while connecting to upstream, client: 10.10.0.40, server: moodle.cpnv-srw3.ch, request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.20.0.11:80/favicon.ico", host: "moodle.cpnv-srw3.ch", referrer: "https://moodle.cpnv-srw3.ch/"
2022/03/28 08:42:02 [error] 467#467: *2896 connect() failed (111: Connection refused) while connecting to upstream, client: 10.10.0.40, server: moodle.cpnv-srw3.ch, request: "GET / HTTP/2.0", upstream: "http://172.20.0.11:80/", host: "moodle.cpnv-srw3.ch", referrer: "https://proxy.cpnv-srw3.ch/"
2022/03/28 08:43:01 [error] 484#484: *2923 connect() failed (111: Connection refused) while connecting to upstream, client: 10.10.0.40, server: moodle.cpnv-srw3.ch, request: "GET / HTTP/2.0", upstream: "http://172.20.0.11:8080/", host: "moodle.cpnv-srw3.ch", referrer: "https://proxy.cpnv-srw3.ch/"
2022/03/28 08:43:03 [error] 484#484: *2923 connect() failed (111: Connection refused) while connecting to upstream, client: 10.10.0.40, server: moodle.cpnv-srw3.ch, request: "GET / HTTP/2.0", upstream: "http://172.20.0.11:8080/", host: "moodle.cpnv-srw3.ch", referrer: "https://proxy.cpnv-srw3.ch/"
2022/03/28 08:44:06 [error] 501#501: *2955 connect() failed (111: Connection refused) while connecting to upstream, client: 10.10.0.40, server: moodle.cpnv-srw3.ch, request: "GET / HTTP/2.0", upstream: "http://172.20.0.11:8443/", host: "moodle.cpnv-srw3.ch", referrer: "https://proxy.cpnv-srw3.ch/"
